import {
  ppNeueMontreal,
  goodMonolith,
  bigShouldersDisplay,
  pangramSans,
} from "./fonts";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import { LoaderProvider } from "@/components/ui/LoaderProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 60;

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${goodMonolith.variable} ${ppNeueMontreal.variable} ${bigShouldersDisplay.variable} ${pangramSans.variable} font-body bg-bg-primary text-text-primary antialiased transition-colors duration-300`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LoaderProvider>{children}</LoaderProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
